# Generated by Django 4.0.6 on 2022-08-04 06:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='upload/default.png', help_text='Profile image for the user', upload_to='upload/')),
                ('full_name', models.CharField(help_text='Full name of the user', max_length=100)),
                ('cnic', models.CharField(help_text='CNIC of the user format: xxxxxx-xxxxxxx-x', max_length=15, validators=[django.core.validators.RegexValidator('\\d{5}\\-\\d{7}\\-\\d{1}', 'CNIC format needs to be - XXXXX-XXXXXXX-X')])),
                ('contact_number', models.CharField(help_text='Phone number of the user format: +xxxxxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{12}$', 'Phone number format needs to be +XXXXXXXXXXXX')])),
                ('address', models.CharField(help_text='Address of the user', max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('', 'Do not specify')], default='', max_length=1)),
                ('country', django_countries.fields.CountryField(help_text='Country of the user', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
