# Generated by Django 4.0.6 on 2022-08-04 07:18

import django.core.validators
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='your home address', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cnic',
            field=models.CharField(blank=True, help_text='your CNIC in the following format: xxxxx-xxxxxxx-x', max_length=15, validators=[django.core.validators.RegexValidator('\\d{5}\\-\\d{7}\\-\\d{1}', 'CNIC format needs to be - XXXXX-XXXXXXX-X')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, help_text='your contact number in the following format: +xxxxxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator('^\\+\\d{12}$', 'Phone number format needs to be +XXXXXXXXXXXX')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='your country', max_length=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text='your full name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='upload/default.png', help_text='your profile picture', upload_to='upload/'),
        ),
    ]
